require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
-- general porpouse

spec "user.alpha"
spec "user.autopairs"
spec "user.cmp"
spec "user.colorizer"
spec "user.colorscheme" -- colorscheme is difined in the file 
spec "user.comment"
spec "user.copilot"
spec "user.copilot-cmp"
spec "user.devicons"
spec "user.diffview" -- neogit
spec "user.gitsigns"
spec "user.glance"
spec "user.illuminate"
spec "user.indentline"
spec "user.lsp-file-ops"
spec "user.lspconfig"
spec "user.lualine"
spec "user.mason"
spec "user.neo-tree"
spec "user.neogit"
spec "user.noice"
spec "user.notify"
spec "user.null-ls"
spec "user.project"
spec "user.telescope"
spec "user.transparent"
spec "user.treesitter"
spec "user.whichkey"
-- spec "user.rainbow-delimiters"
-- filetype related plugins
spec "user.filetype.jdtls"
spec "user.filetype.vimtex"
spec "user.filetype.prettier"
spec "user.filetype.lean"
require "user.lazy"
